use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Users::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Users::Id)
                            .string_len(36)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Users::PrimaryWalletAddress)
                            .string_len(42)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Users::Email).string_len(255))
                    .col(
                        ColumnDef::new(Users::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Users::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AuthMethods::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AuthMethods::Id)
                            .string_len(36)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AuthMethods::UserId)
                            .string_len(36)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthMethods::MethodType)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthMethods::ExternalId)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AuthMethods::Meta)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'::jsonb")),
                    )
                    .col(
                        ColumnDef::new(AuthMethods::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AuthMethods::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AuthMethods::Table, AuthMethods::UserId)
                            .to(Users::Table, Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(AuthMethods::MethodType)
                            .col(AuthMethods::ExternalId),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(VenueConnections::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(VenueConnections::Id)
                            .string_len(36)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::UserId)
                            .string_len(36)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::Venue)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::AccountIdentifier)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::Config)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'::jsonb")),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::Enabled)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::Limits)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'::jsonb")),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(VenueConnections::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(VenueConnections::Table, VenueConnections::UserId)
                            .to(Users::Table, Users::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(VenueConnections::UserId)
                            .col(VenueConnections::Venue),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(VenueConnections::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(AuthMethods::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Users::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Users {
    Table,
    Id,
    PrimaryWalletAddress,
    Email,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum AuthMethods {
    Table,
    Id,
    UserId,
    MethodType,
    ExternalId,
    Meta,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum VenueConnections {
    Table,
    Id,
    UserId,
    Venue,
    AccountIdentifier,
    Config,
    Enabled,
    Limits,
    CreatedAt,
    UpdatedAt,
}
